baseurl: https://social-protocols.org/
languageCode: en-us
title: Social Protocols
theme: hugo-lithium
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:slug/
summaryLength: 30
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: /about/
      weight: 2
  footer:
    - name: GitHub
      url: https://github.com/social-protocols
    - name: Twitter
      url: https://twitter.com/socialprotocols
    - name: Mastodon
      url: https://mas.to/@SocialProtocols
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A website built through Hugo and blogdown.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0

  # Uncommenet this later to add a logo
  # logo:
  #   alt: Logo
  #   height: 50
  #   url: logo.png
  #   width: 50

outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "rss"

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
