---
title: Social Protocols
site: distill::distill_website
---

The goal of *Social Protocols* is to enhance collective intelligence. We are working on open algorithms and protocols that benefit large scale human interaction.

Our first experiment, [Quality News](https://news.social-protocols.org), is about helping communities to collectively allocate their attention. We propose a news-aggregator ranking formula which reflects the intent revealed by the voting behavior of the community. It should help the community to focus and drive more intelligent conversations.

We have chosen Hacker News as a starting point for experimenting with social protocols because of the existing community, open API, and proven ranking algorithm. Our hope is to draw enough users to run bigger, open experiments in the future.

Follow us on <a rel="me" href="https://mas.to/@SocialProtocols">Mastodon</a> or <a href="https://twitter.com/socialprotocols">Twitter</a>, or send a <a href="mailto:mail@social-protocols.org">mail<a>.
