name: Build & Publish

on:
  push:
    branches: [main]
  workflow_dispatch:
  pull_request:

# automatically cancel previous runs on the same PR
# https://stackoverflow.com/questions/66335225/how-to-cancel-previous-runs-in-the-pr-when-you-push-new-commitsupdate-the-curre/67939898#67939898
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # https://github.com/rstudio/ai-blog/blob/c07dff9c18859ba682ee112ed45c7c3115c86e71/.github/workflows/main.yml#L15


      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v1

      - name: Cache R Packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ hashFiles('.github/R-version') }}-${{ hashFiles('.github/pkg-versions.Rds') }}-${{ hashFiles('.github/pkg-deps.Rds') }}
          restore-keys: ${{ hashFiles('.github/R-version') }}-

      - name: Install distill
        run: Rscript -e 'install.packages("distill")'
      - name: build website
        run: Rscript -e 'rmarkdown::render_site()'
      # - uses: r-lib/actions/setup-pandoc@v1
      # - name: Install rmarkdown
      #   run: Rscript -e 'install.packages("rmarkdown")'
      # - name: Render README
      #   run: Rscript -e 'rmarkdown::render("index.Rmd", output_format = "md_document")'
      # - name: Commit results
      #   run: |
      #     git commit README.md -m 'Re-build README.Rmd' || echo "No changes to commit"
      #     git push origin || echo "No changes to commit"
